export const themes = {
  'light': {
    '--text-color-normal': '#4a4a4a',
    '--text-color-light': '#dbdbdb',
    '--text-color-link': '#3273dc',
    '--text-color-link--hover': '#363636',
    '--text-color-link--visited': '#551A8B',
    '--background': '#fefefe',
    '--background-hover': '#fafafa',
    '--border-color':'#dfdfdf',
    '--card-border': '#dbdbdb',
    '--card-box-shadow': '0 2px 3px rgba(10,10,10,.1)',
    '--logo-fill': '#000',
    '--input-error-color': '#f00',
    '--searchbar-background-color': '#fff',
    '--searchbar-border-color': '#e7e7e7',
    '--searchbar-text-color': '#dbdbdb',
    '--urkel-color': '#ee8c3a',
    '--ha-color': '#532ad1',
  },
  "dark": {
    '--text-color-normal': '#afafaf',
    '--text-color-light': '#969696',
    '--text-color-link': '#3273dc',
    '--text-color-link--hover': '#cfcfcf',
    '--text-color-link--visited': '#551A8B',
    '--background': '#323232',
    '--background-hover': '#454545',
    '--border-color':'#575757',
    '--card-background': '#373737',
    '--card-border': '#dbdbdb',
    '--card-box-shadow': '0 2px 3px rgba(10,10,10,.1)',
    '--logo-fill': '#cfcfcf',
    '--input-error-color': '#f00',
    '--searchbar-background-color': '#575757',
    '--searchbar-border-color': '#969696',
    '--searchbar-text-color': '#dbdbdb',
    '--urkel-color': '#ee8c3a',
    '--ha-color': '#532ad1',
  }
}
