name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: eslint #convert this only to run on PRs?
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'
      - name: yarn build, and test
        run: |
          yarn
          yarn build
          yarn test
        env:
          CI: true
