name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: borales/actions-yarn@v2.0.0
      with:
          cmd: install
    - name: npm install, build, and test
      run: |
        yarn build
        yarn test
      env:
        CI: true
